[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm cache clean --force && npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"
  SKIP_PREFLIGHT_CHECK = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "*.tsx"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "*.ts"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
